package com.Ecommerce.demo.Util.Email.EmailContent;

public class CustomerRegistration {

    public static String buildWelcomeEmail(String firstName, String lastName, int loyaltyPoints) {
        StringBuilder emailBuilder = new StringBuilder();

        emailBuilder.append("<!DOCTYPE html>")
                .append("<html lang=\"en\">")
                .append("<head>")
                .append("<meta charset=\"UTF-8\">")
                .append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
                .append("<title>Welcome to VEMOS</title>")
                .append("<link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Playfair+Display:wght@700&display=swap\" rel=\"stylesheet\">")
                .append("<style>")
                .append("body {")
                .append("font-family: 'Montserrat', sans-serif;")
                .append("line-height: 1.6;")
                .append("margin: 0;")
                .append("padding: 0;")
                .append("background-color: #f5f5f5;")
                .append("color: #333;")
                .append("}")
                .append(".container {")
                .append("max-width: 600px;")
                .append("margin: 20px auto;")
                .append("background: white;")
                .append("border-radius: 8px;")
                .append("overflow: hidden;")
                .append("box-shadow: 0 0 15px rgba(0,0,0,0.1);")
                .append("}")
                .append(".header {")
                .append("background-color: #776733;")
                .append("color: white;")
                .append("padding: 40px 20px;")
                .append("text-align: center;")
                .append("}")
                .append(".header h1 {")
                .append("margin: 0;")
                .append("font-size: 32px;")
                .append("font-family: 'Playfair Display', serif;")
                .append("font-weight: 700;")
                .append("letter-spacing: 1px;")
                .append("}")
                .append(".content {")
                .append("padding: 40px;")
                .append("color: #555;")
                .append("}")
                .append("h2 {")
                .append("font-family: 'Playfair Display', serif;")
                .append("color: #776733;")
                .append("font-weight: 700;")
                .append("margin-top: 0;")
                .append("}")
                .append(".footer {")
                .append("background-color: #000;")
                .append("color: #fff;")
                .append("text-align: center;")
                .append("padding: 25px;")
                .append("font-size: 12px;")
                .append("}")
                .append(".button {")
                .append("display: inline-block;")
                .append("background-color: #000;")
                .append("color: white;")
                .append("text-decoration: none;")
                .append("padding: 15px 30px;")
                .append("border-radius: 30px;")
                .append("margin: 25px 0;")
                .append("font-weight: 600;")
                .append("letter-spacing: 0.5px;")
                .append("transition: all 0.3s ease;")
                .append("}")
                .append(".button:hover {")
                .append("background-color: #333;")
                .append("transform: translateY(-2px);")
                .append("box-shadow: 0 4px 8px rgba(0,0,0,0.1);")
                .append("}")
                .append(".points-container {")
                .append("text-align: center;")
                .append("margin: 30px 0;")
                .append("padding: 30px 0;")
                .append("border-top: 1px dashed #e1e1e1;")
                .append("border-bottom: 1px dashed #e1e1e1;")
                .append("}")
                .append(".points-badge {")
                .append("background-color: #f8f3e6;")
                .append("border: 2px solid #e1d9c3;")
                .append("border-radius: 30px;")
                .append("padding: 15px 30px;")
                .append("display: inline-block;")
                .append("font-weight: 600;")
                .append("color: #776733;")
                .append("font-size: 18px;")
                .append("box-shadow: 0 4px 15px rgba(119, 103, 51, 0.1);")
                .append("}")
                .append(".highlight {")
                .append("font-size: 24px;")
                .append("font-weight: 700;")
                .append("color: #776733;")
                .append("}")
                .append("@media only screen and (max-width: 600px) {")
                .append(".container {")
                .append("width: 100%;")
                .append("border-radius: 0;")
                .append("}")
                .append(".content, .header {")
                .append("padding: 25px 15px;")
                .append("}")
                .append(".button {")
                .append("padding: 12px 25px;")
                .append("}")
                .append("}")
                .append("</style>")
                .append("</head>")
                .append("<body>")
                .append("<div class=\"container\">")
                .append("<div class=\"header\">")
                .append("<h1>Welcome to VEMOS</h1>")
                .append("</div>")
                .append("<div class=\"content\">")
                .append("<h2>Dear ").append(firstName).append(" ").append(lastName).append(",</h2>")
                .append("<p>We're absolutely delighted to welcome you to the VEMOS family! Your journey with us begins now, and we can't wait to show you what we have in store.</p>")
                .append("<p>As a valued member of our community, we're committed to providing you with exceptional experiences that go beyond the ordinary.</p>")
                .append("<div class=\"points-container\">")
                .append("<div class=\"points-badge\">")
                .append("<span class=\"highlight\">").append(loyaltyPoints).append("</span> loyalty points awarded!")
                .append("</div>")
                .append("</div>")
                .append("<p>Your points are already in your account, ready to be redeemed for exclusive benefits and rewards.</p>")
                .append("<center>")
                .append("<a href=\"https://www.vemos.com\" class=\"button\">DISCOVER VEMOS</a>")
                .append("</center>")
                .append("<p>Should you need anything at all, our dedicated team is here to help. Welcome to a world of possibilities!</p>")
                .append("<p>With warm regards,<br>")
                .append("<strong>The VEMOS Team</strong></p>")
                .append("</div>")
                .append("<div class=\"footer\">")
                .append("&copy; 2023 VEMOS. All rights reserved.<br>")
                .append("[Company Address] | [City, State ZIP]<br>")
                .append("<a href=\"#\" style=\"color: #aaa; text-decoration: none;\">Unsubscribe</a> | ")
                .append("<a href=\"#\" style=\"color: #aaa; text-decoration: none;\">Privacy Policy</a>")
                .append("</div>")
                .append("</div>")
                .append("</body>")
                .append("</html>");

        return emailBuilder.toString();
    }
}
