package com.Ecommerce.demo.Util.Email.EmailContent;


public final class CustomerForgotPassword {

    /**
     * Builds the HTML content for the OTP email sent to customers who forgot their password.
     *
     * @param firstName The first name of the customer.
     * @param lastName  The last name of the customer.
     * @param otp       The One-Time Password (OTP) for password reset.
     * @return A String containing the HTML content of the email.
     */
    public static String buildOtpEmail(String firstName, String lastName, String otp) {
        StringBuilder emailBuilder = new StringBuilder();

        emailBuilder.append("<!DOCTYPE html>")
                .append("<html lang=\"en\">")
                .append("<head>")
                .append("<meta charset=\"UTF-8\">")
                .append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
                .append("<title>Password Reset OTP | VEMOS</title>")
                .append("<style>")
                .append("body {")
                .append("font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;")
                .append("line-height: 1.6;")
                .append("margin: 0;")
                .append("padding: 0;")
                .append("background-color: #f7f7f7;")
                .append("color: #333333;")
                .append("}")
                .append(".container {")
                .append("max-width: 600px;")
                .append("margin: 20px auto;")
                .append("background: #ffffff;")
                .append("border-radius: 8px;")
                .append("overflow: hidden;")
                .append("box-shadow: 0 0 20px rgba(0,0,0,0.05);")
                .append("}")
                .append(".header {")
                .append("background-color: #776733;")
                .append("color: white;")
                .append("padding: 30px 20px;")
                .append("text-align: center;")
                .append("}")
                .append(".header h1 {")
                .append("margin: 0;")
                .append("font-size: 24px;")
                .append("font-weight: 600;")
                .append("}")
                .append(".content {")
                .append("padding: 40px;")
                .append("color: #555555;")
                .append("}")
                .append(".otp-code {")
                .append("font-size: 32px;")
                .append("letter-spacing: 5px;")
                .append("color: #776733;")
                .append("font-weight: 700;")
                .append("text-align: center;")
                .append("margin: 30px 0;")
                .append("padding: 15px;")
                .append("background-color: #f8f7f3;")
                .append("border-radius: 6px;")
                .append("border: 1px dashed #d1c7a7;")
                .append("}")
                .append(".button {")
                .append("display: inline-block;")
                .append("background-color: #000000;")
                .append("color: white;")
                .append("text-decoration: none;")
                .append("padding: 15px 30px;")
                .append("border-radius: 30px;")
                .append("margin: 20px 0;")
                .append("font-weight: 600;")
                .append("transition: background-color 0.3s;")
                .append("}")
                .append(".button:hover {")
                .append("background-color: #333333;")
                .append("}")
                .append(".footer {")
                .append("background-color: #000000;")
                .append("color: #ffffff;")
                .append("text-align: center;")
                .append("padding: 20px;")
                .append("font-size: 12px;")
                .append("}")
                .append(".timer {")
                .append("color: #d9534f;")
                .append("font-weight: 600;")
                .append("}")
                .append(".divider {")
                .append("border-top: 1px solid #eeeeee;")
                .append("margin: 25px 0;")
                .append("}")
                .append("@media only screen and (max-width: 600px) {")
                .append(".container {")
                .append("border-radius: 0;")
                .append("margin: 0;")
                .append("}")
                .append(".content {")
                .append("padding: 30px 20px;")
                .append("}")
                .append(".otp-code {")
                .append("font-size: 28px;")
                .append("padding: 12px;")
                .append("}")
                .append("}")
                .append("</style>")
                .append("</head>")
                .append("<body>")
                .append("<div class=\"container\">")
                .append("<div class=\"header\">")
                .append("<h1>Password Reset Request</h1>")
                .append("</div>")
                .append("<div class=\"content\">")
                .append("<h2>Hello ").append(firstName).append(" ").append(lastName).append(",</h2>")
                .append("<p>We received a request to reset your VEMOS account password. Here's your One-Time Password (OTP):</p>")
                .append("<div class=\"otp-code\">")
                .append(otp)
                .append("</div>")
                .append("<p>This code expires in <span class=\"timer\">10 minutes</span>. Do not share it with anyone.</p>")
                .append("<center>")
                .append("<a href=\"https://www.vemos.com/reset-password\" class=\"button\">RESET PASSWORD</a>")
                .append("</center>")
                .append("<div class=\"divider\"></div>")
                .append("<p><strong>Didn't request this?</strong> Ignore this email or contact us immediately at support@vemos.com</p>")
                .append("</div>")
                .append("<div class=\"footer\">")
                .append("&copy; 2023 VEMOS. All rights reserved.<br>")
                .append("[Company Address] | [City, State ZIP]<br>")
                .append("<a href=\"#\" style=\"color: #aaaaaa; text-decoration: none;\">Unsubscribe</a> | ")
                .append("<a href=\"#\" style=\"color: #aaaaaa; text-decoration: none;\">Privacy Policy</a>")
                .append("</div>")
                .append("</div>")
                .append("</body>")
                .append("</html>");

        return emailBuilder.toString();
    }

}
