package com.Ecommerce.demo.Util.Email.EmailContent;

public final class WaitingListArrival {

    public static String buildWaitingListEmail(String firstName, String lastName,
                                               String productName, String productImage,
                                               String size, String material,
                                               String productUrl) {
        StringBuilder emailBuilder = new StringBuilder();

        emailBuilder.append("<!DOCTYPE html>")
                .append("<html lang=\"en\">")
                .append("<head>")
                .append("<meta charset=\"UTF-8\">")
                .append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
                .append("<title>Your Jewelry Item Is Available | VEMOS</title>")
                .append("<style>")
                .append("body {font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;line-height: 1.6;margin: 0;padding: 0;background-color: #f7f7f7;color: #333333;}")
                .append(".container {max-width: 600px;margin: 20px auto;background: #ffffff;border-radius: 8px;overflow: hidden;box-shadow: 0 0 20px rgba(0,0,0,0.05);}")
                .append(".header {background-color: #776733;color: white;padding: 30px 20px;text-align: center;}")
                .append(".header h1 {margin: 0;font-size: 24px;font-weight: 600;}")
                .append(".content {padding: 30px;color: #555555;}")
                .append(".product-container {display: flex;margin: 25px 0;border: 1px solid #eeeeee;border-radius: 8px;overflow: hidden;}")
                .append(".product-image {width: 40%;background-color: #f8f7f3;display: flex;align-items: center;justify-content: center;}")
                .append(".product-image img {max-width: 100%;height: auto;display: block;}")
                .append(".product-details {width: 60%;padding: 20px;background-color: #ffffff;}")
                .append(".product-title {font-size: 18px;font-weight: 600;margin: 0 0 10px 0;color: #222222;}")
                .append(".product-attributes {margin: 10px 0;font-size: 14px;}")
                .append(".product-attribute {margin-bottom: 5px;}")
                .append(".attribute-label {font-weight: 600;color: #776733;display: inline-block;width: 80px;}")
                .append(".button {display: inline-block;background-color: #000000;color: white;text-decoration: none;padding: 15px 30px;border-radius: 30px;margin: 20px 0;font-weight: 600;transition: background-color 0.3s;}")
                .append(".button:hover {background-color: #333333;}")
                .append(".footer {background-color: #000000;color: #ffffff;text-align: center;padding: 20px;font-size: 12px;}")
                .append(".divider {border-top: 1px solid #eeeeee;margin: 25px 0;}")
                .append("@media only screen and (max-width: 480px) {")
                .append(".container {border-radius: 0;margin: 0;}")
                .append(".content {padding: 20px 15px;}")
                .append(".product-container {flex-direction: column;}")
                .append(".product-image, .product-details {width: 100%;}")
                .append(".product-image {height: 200px;}}")
                .append("</style>")
                .append("</head>")
                .append("<body>")
                .append("<div class=\"container\">")
                .append("<div class=\"header\">")
                .append("<h1>Your Waitlist Item Is Available!</h1>")
                .append("</div>")
                .append("<div class=\"content\">")
                .append("<h2>Hello ").append(firstName).append(" ").append(lastName).append(",</h2>")
                .append("<p>We're excited to let you know that the jewelry item you've been waiting for is now back in stock!</p>")
                .append("<div class=\"product-container\">")
                .append("<div class=\"product-image\">")
                .append("<img src=\"").append(productImage).append("\" alt=\"Your Jewelry Item\">")
                .append("</div>")
                .append("<div class=\"product-details\">")
                .append("<h3 class=\"product-title\">").append(productName).append("</h3>")
                .append("<div class=\"product-attributes\">")
                .append("<div class=\"product-attribute\">")
                .append("<span class=\"attribute-label\">Material:</span>")
                .append("<span>").append(material).append("</span>")
                .append("</div>")
                .append("<div class=\"product-attribute\">")
                .append("<span class=\"attribute-label\">Size:</span>")
                .append("<span>").append(size).append("</span>")
                .append("</div>")
                .append("<div class=\"product-attribute\">")
                .append("<span class=\"attribute-label\">Status:</span>")
                .append("<span style=\"color: #28a745; font-weight: 600;\">Available Now</span>")
                .append("</div>")
                .append("</div>")
                .append("</div>")
                .append("</div>")
                .append("<p>Hurry! This item is in high demand and may sell out quickly.</p>")
                .append("<center>")
                .append("<a href=\"").append(productUrl).append("\" class=\"button\">SHOP NOW</a>")
                .append("</center>")
                .append("<div class=\"divider\"></div>")
                // The "No longer interested?" paragraph has been removed here
                .append("</div>")
                .append("<div class=\"footer\">")
                .append("&copy; 2023 VEMOS. All rights reserved.<br>")
                .append("[Company Address] | [City, State ZIP]<br>")
                .append("<a href=\"#\" style=\"color: #aaaaaa; text-decoration: none;\">Unsubscribe</a> | ")
                .append("<a href=\"#\" style=\"color: #aaaaaa; text-decoration: none;\">Privacy Policy</a>")
                .append("</div>")
                .append("</div>")
                .append("</body>")
                .append("</html>");

        return emailBuilder.toString();
    }
}
